# BY CSS SELECTOR
nodo = ".texto-header-unificado.nombre-servidor-header-unificado.z-label"
logo = ".flex-item-header-unificado.logo-header-unificado.z-image"

boton_inicio_documento = "//button[normalize-space()='Inicio de Documento']"
input_acronimo = ".z-bandbox-input"
boton_producir_yo_mismo = "button[title='Continuar con la tarea de producción del documento.']"
input_motivo = "//tbody/tr[@class='GridLayoutNoBorder z-row']/td[@class='z-cell']/input[1]"
boton_destinatarios = "//button[normalize-space()='Destinatarios']"
input_destinatario = "//body[1]/div[7]/div[2]/div[4]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[5]/div[1]/span[1]/input[1]"
boton_cargar = "//button[normalize-space()='Cargar']"
boton_aceptar = "//button[normalize-space()='Aceptar']"
boton_firmar_yo_mismo = "//button[normalize-space()='Firmar Yo Mismo el Documento']"
boton_firmar_con_certificado = "//button[normalize-space()='Firmar con Certificado']"
span_nro_gedo = "//span[contains(text(),'Se ha generado correctamente el documento y se le ')]"