# BY 
nodo = ".texto-header-unificado.nombre-servidor-header-unificado.z-label"
logo = ".flex-item-header-unificado.logo-header-unificado.z-image"
boton_caratular_interno = "div[class='z-tabpanels'] div:nth-child(2) button:nth-child(1)"
textarea_motivo_interno = "tr[class='z-row'] textarea[class='z-textbox']"
textarea_motivo_externo = "textarea[title='Debe ingresar Motivo Externo. Este corresponde a la motivación que se visualizará en la consulta pública.']"
input_codigo_tramite = "//tbody/tr[@class='z-row']/td[@class='z-cell']/span[@class='z-bandbox']/input[1]"
textarea_descripcion_adicional = "//body[1]/div[3]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[7]/td[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/textarea[1]"
boton_caratular = "//tbody/tr[@valign='top']/td[1]/button[1]"
boton_ok = "button[class='z-messagebox-button z-button']"
span_nro_expediente = "div[class='z-messagebox z-div'] span[class='z-label']"
input_busqueda = "input[placeholder='Ingrese el número GDEBA']"
boton_buscar = "button[title='Buscar']"
expediente_encontrado = "body > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(7) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(8) > div:nth-child(3) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1) > div:nth-child(1)"
boton_ejecutar = "//body[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[9]/div[3]/table[1]/tbody[1]/tr[1]/td[9]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/span[1]"
boton_realizar_pase = "button[title='El pase sólo puede realizarse si no se presentan pendientes de confirmación en Tramitación Conjunta y/o Fusión.']"
iframe_ckeditor = "//iframe[@class='cke_wysiwyg_frame cke_reset']"
combobox_estado = "span[class='z-combobox z-combobox-readonly'] input[value='Iniciación']"
boton_realizar_pase_2 = "//div[@align='center']//button[@type='button'][normalize-space()='Realizar Pase']"
boton_si = "//button[normalize-space()='Si']"
boton_ok_2 = "//button[normalize-space()='OK']"
boton_crear_nueva_solicitud = "//button[normalize-space()='Crear Nueva Solicitud']"
boton_solicitar_caratulacion = "//button[normalize-space()='Solicitar Caratulación']"
checkbox_usuario = "input[value='usuario']"
input_usuario = ".z-combobox-input.z-combobox-rightedge"
boton_enviar_solicitud = "//button[normalize-space()='Enviar Solicitud']"
boton_realizar_pase_3 = "//button[normalize-space()='Realizar Pase']"
checkbox_pase_block_1 = "//div[@class='z-window z-window-modal z-window-shadow']//div[@class='z-listbox-body']//table[1]//tbody[1]//tr[1]//td[1]"
boton_generar_pase_bloque = "//button[normalize-space()='Generar Pase']"
span_realizado = "//div[normalize-space()='Realizado']"