# BY CSS SELECTOR
nodo = ".texto-header-unificado.nombre-servidor-header-unificado.z-label"
logo = ".flex-item-header-unificado.logo-header-unificado.z-image"

boton_inicio_documento = "//button[normalize-space()='Inicio de Documento']"
input_acronimo = ".z-bandbox-input"
boton_producir_yo_mismo = "button[title='Continuar con la tarea de producción del documento.']"
input_motivo = "//tbody/tr[@class='GridLayoutNoBorder z-row']/td[@class='z-cell']/input[1]"
boton_firmar_yo_mismo = "//button[normalize-space()='Firmar Yo Mismo el Documento']"
boton_firmar_con_certificado = "//button[normalize-space()='Firmar con Certificado']"
span_nro_gedo = "//span[contains(text(),'Se ha generado correctamente el documento y se le ')]"
boton_portafirma = "//span[normalize-space()='Porta Firma']"
boton_firmar_seleccionados = "//button[@title='Firmar las solicitudes seleccionadas en la lista']"
boton_volver = "//button[normalize-space()='Volver']"
#Se agregó esta parte para verificar si funciona el portafirma.py
boton_portafirma_configuracion= "body .z-tabbox .z-tabpanels li:nth-child(3) > a > .z-tab-text"
activar_portafirma="//span[normalize-space()='Activar Porta Firma']"
boton_guardar="//button[normalize-space()='Guardar']"
boton_mis_tareas = "//span[normalize-space()='Mis Tareas']"
boton_OK = "//button[normalize-space()='OK']"
